### PR TITLE
git submodule and macOS Build Support

### PR DESCRIPTION
**Pull request by rschiang**
This pull request enables enve to be built and run on macOS.

mac

The first part of the commit replaces the binaries with git submodules. ([it’s generally a bad idea to commit them into the repository](http://web.archive.org/web/20181011004501/https://robinwinslow.uk/2013/06/11/dont-ever-commit-binary-files-to-git/), if you wonder.) Ditching binaries and switching to git submodules not only help keep the repository size small, updating new versions for these dependencies will also be much more easier.

The second part of the commit fixes several issues raised by the clang compiler, primarily header filename differences or missing includes. There are also a few ambiguities when resolving overload template functions in `eTextStream`, which are also addressed.

This “pilot” build was compiled against Qt 5.14.2 on macOS 10.14 with Homebrew and has successfully run on Debug and Release configurations. I’ll keep this open while ~~I update README with macOS specific instructions~~ **(done)**, but hope this PR gives a headway on where I’m going. 😉 

### Update: To-dos

- [X] Switch to git submodules
- [X] Update README with macOS build instructions
- [x] Make sure it doesn't break Linux builds
- [x] Update CI configuration

### CODE REVIEW

**Comment by MaurycyLiebner** [comment]
Using submodules was long overdue, I never got to it. I don't even know how to work with them, so thank you for getting it done.

Thank you for your time and effor. It would take me a lot of time to successfully build enve on mac.
I know nothing about macOS, I used it for few years, but it was 15 years ago.

`download.qt.io` is down, that's why the Travis build failed. I will try to restart it when the server is back online.

I will try setting up macOS virtual machine to test the build instructions once you complete them.
Since Travis CI supports macOS it would make a lot of sense to use it.

I see there are some issues with menu bars on macOS.

**Comment by rschiang** [comment]
@MaurycyLiebner I’m glad you’re open to this! It also took me a few months before I got comfortable with git submodules, but they saved a lot of time once onboard.

I’ve already updated the README file with `clang`-specific build instructions. Could you test if the code still builds under Ubuntu? If the code change works, I could probably help with streamlining the build/linking process and/or start fixing bugs on macOS. 

Thanks again for bringing us the awesome project!

**Comment by MaurycyLiebner** [comment]
The easiest way to check the Ubuntu build is to update `.travis.yml` so that it doesn't try to extract missing archives. I am not 100% sure, but I think Travis should download submodules on its own.
All you have to do is remove `tar xf [ARCHIVE]` for all archives you replaced with submodules, e.g., remove `tar xf libmypaint.tar.xz,` and replace `cd [FOLDER]` with submodule folders, e.g., replace `cd libmypaint-1.5.1` with `cd libmypaint`

Please note that gperftools-2.7-enve-mod is slightly different than plain gperftools. I added a helper function that uses private gperftools code, that's why you cannot use brew-installed gperftools.
Gperftools is needed on Linux to retrieve memory usage.
I am not sure what would be the best way to get this info on macOS (see memorychecker.cpp).

**Comment by MaurycyLiebner** [comment]
I replaced menu bars with regular widgets, with the exception of the main menu bar. I think this should fix the menu bar issue under macOS (make menu bars visible).

Sadly, it seems that I cannot use macOS in virtual machine. I have AMD CPU, and they are not supported.

When the current PR is done, it would be great to make the macOS version fully functional, I think all that is needed is **MemoryChecker::sGetFreeKB** (memorychecker.cpp) and **getTotalRamBytes** (hardwareinfo.cpp) implementations.

**MemoryChecker::sGetFreeKB** - retrieves free physical memory
**getTotalRamBytes** - retrieves total physical memory

I already did some digging in that regard, it shouldn't be too difficult.

**Comment by rschiang** [comment]
Oops, I just sorted the menu bar stuff out and working on another patch for that. Not sure about things other than main menu (still getting acquainted with Enve), but for main menu, only one line is needed to make it work (`mainwindow.cpp` line 257):

```
mMenuBar = new QMenuBar(nullptr);
```

As of `gperftool`, I think turning it into git submodule + patch might work; but as there are more urgent UI issues (e.g. GL window does not scale with HiDPI screen), I guess that could be done later. For now, I'll try to tweak CI settings first.

**Comment by MaurycyLiebner** [comment]
Given the changes in the way libmypaint headers are included, I think `sudo make install` is missing from `.travis.yml` for libmypaint, that's why Travis fails.

**Comment by rschiang** [comment]
Since the project directly linked from build directory and the fact that I merely replaced the source with submodules, it shouldn’t break anything if the source was pristine.

**UPDATE**: I eventually managed to build `libmypaint` and link Enve with it on macOS. It seems that the actual build script from `libmypaint` does not generate `include` directory at all if cloned from `git`. I changed the include directory accordingly and added a symbolic link; it should be working by now.

The reason why `make install` would work is that it would install the headers to `/usr` or `/usr/local`, making them available system-wide. Though it might work with CI, it would let project configurations hard to reproduce or diagnose.

**Comment by rschiang** [comment]
Great! Building Skia from source and linking it statically needs `-lfontconfig` in addition. I’ll run a quick check to see if macOS builds are still up (with `--enable-openmp`), and then it would be good to go.

**Comment by rschiang** [comment]
All clear and ready to merge! Linker sequence was a bit tricky but managed to get it right on macOS and Linux (CI). 🎉

**Comment by MaurycyLiebner** [comment]
Great job!

**Comment by MaurycyLiebner** [comment]
I implemented Travis CI for macOS, continuous macOS releases are available on GitHub.
I tried blind-implementing memory handling for macOs.
Sadly, I cannot even test whether the dmg file actually works.
Could you test it? The best way to test memory handling is to create and preview a simple long animated scene, so that enve runs out of memory. When it runs out of memory it should automatically start the preview. When the preview finishes you can try playing it again to see whether enve properly calculates and releases free memory. The length  of the second preview should be roughly the same as the length of the first preview.

**Pull request merged**
